// Generated by https://quicktype.io

export interface AuthUserResponse {
  user: AuthUserType;
  token: string;
}

export interface AuthUserType {
  _id: string;
  email: string;
  name: string;
  isActive: boolean;
  roles: string[];
}

export type UserAuthReqType = {
  name?: string;
  email: string;
  password: string;
};

export enum AuthStatus {
  cheking = 'cheking',
  authenticated = 'authenticated',
  notAuthenticated = 'notAuthenticated',
}
